### ISSUE TITLE
Why is this repo not gaining traction?

### ISSUE THREAD

**Issue by offchan42** [pvys/CV-camera-finder#1]
It seems that your repo solves my problem very well. I only need to copy the `pymf.pyd` file into my project and then run 2 lines to get my list of camera names ordered like OpenCV. While other approaches I tried are difficult and not working well.
![image](https://user-images.githubusercontent.com/15215732/78893666-e772d600-7a95-11ea-9e5f-adeb527b1cd0.png)

But is there a catch with this approach?
Because if it's good it should gain traction, no?

**Comment by pvys** [comment]
Hi @off99555! Thanks for liking it!
well, I haven't seen any bugs or side effects yet. For not so popular thing, you know, it's just a really simple repo, only one function in python which can only be used on windows with MSMF : )
