### ISSUE TITLE
Also bundle win32 binary

### ISSUE THREAD

**Issue by EhsanKia** [pvys/CV-camera-finder#2]
This is awesome, but I think the binary release is only the 64bit version. Any chance you could also distribute the 32bit version for people run python in win32?

Cheers, this is an awesome project!

**Comment by pvys** [comment]
Hi @EhsanKia, Thanks for pointing it out!
I just added binary for 32bit version. Does it work?

**Comment by EhsanKia** [comment]
Sorry forgot to reply, it works perfectly thank you!
